www:
  environment:
    MYSERVICES: www
  image: kbase/depl:1.0
  ports:
   - 8080:80
   - 8443:443
  links:
   - shock
   - handleservice
   - narrative
   - authorization
   - handlemngr 
   - ws 
   - narrativemethodstore
   - ujs
   - awe
   - njswrapper
   - narrativejobservice
   - transform
   - userprofile
  command: /usr/sbin/nginx
authorization:
  image: kbase/depl:1.0
  expose:
   - 7039
  external_links:
   - mongo
  environment:
    MYSERVICES: authorization
awe:
  image: kbase/depl:1.0
  expose:
   - 7107
   - 7108
  external_links:
   - mongo
  environment:
    MYSERVICES: awe
shock:
  image: kbase/depl:1.0
  expose:
   - 7044
  external_links:
   - mongo
  environment:
    MYSERVICES: shock
  volumes:
   - /data/docker/shock:/mnt/Shock
handleservice:
  image: kbase/depl:1.0
  expose:
   - 7109
  links:
   - shock
  external_links:
   - mysql
  environment:
    MYSERVICES: handle_service
handlemngr:
  image: kbase/depl:1.0
  expose:
   - 9001
  links:
   - handleservice
  environment:
    MYSERVICES: HandleMngr
ws:
  image: kbase/depl:1.0
  expose:
   - 7058
  links:
   - shock
   - handlemngr
   - handleservice
  external_links:
   - mongo
  environment:
    MYSERVICES: Workspace
narrativemethodstore:
  image: kbase/depl:1.0
  expose:
   - 7125
  environment:
    MYSERVICES: NarrativeMethodStore
ujs:
  image: kbase/depl:1.0
  expose:
   - 7083
  external_links:
   - mongo
  environment:
    MYSERVICES: UserAndJobState
njswrapper:
  image: kbase/depl:1.0
  #queue.db.dir=/tmp/njs/queue
  links:
   - ujs
   - ws
   - narrativejobservice
  expose:
   - 8200
  environment:
    MYSERVICES: NarrativeJobService
narrativejobservice:
  image: kbase/depl:1.0
  links:
   - ws
   - awe
   - shock
  expose:
   - 7080
  environment:
    MYSERVICES: NarrativeJobService
narrative:
  image: kbase/depl:1.0
  ports:
   - 9080:80
   - 9443:443
  environment:
    MYSERVICES: narrativex
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock 
   - /dev/log:/dev/log
transform:
  image: kbase/depl:1.0
  links:
   - shock
   - ujs
   - ws
   - awe
  expose:
   - 7778
  environment:
    MYSERVICES: Transform
userprofile:
  image: kbase/depl:1.0
  expose:
   - 7126
  external_links:
   - mongo
  environment:
    MYSERVICES: UserProfile
